name: stream_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  better_player: ^0.0.84
  bloc: ^8.1.4
  connectivity_plus: ^6.0.5
  equatable: ^2.0.5
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_downloader: ^1.11.8
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  intl: ^0.19.0
  path_provider: ^2.1.4

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  ios: true
  android: true # android icon already generate by android studio
  image_path_ios: "assets/icons/play_arrow.png"
  image_path_android: "assets/icons/play_arrow.png"
  adaptive_icon_background: "assets/icons/background.png"
